# Generated by Django 5.1.7 on 2025-04-05 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings_group', '0003_savingsgroupmember'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='owner_type',
            field=models.CharField(choices=[('user', 'user'), ('savings_group_member', 'savings_group_member')], max_length=20),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_wallet', to='wallet.wallet')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_wallet', to='wallet.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('requested_savings_group_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_wallet_group', to='wallet.wallet')),
                ('requester_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester_wallet', to='wallet.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_description', models.TextField()),
                ('rule_type', models.CharField(choices=[('exact', 'Exact Contribution'), ('time_based', 'Time-based Contribution'), ('flexible', 'Flexible Withdrawal'), ('min_balance', 'Minimum Balance Requirement'), ('other', 'Other')], max_length=20)),
                ('max_withdrawal_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_balance_required', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exact_contribution_required', models.BooleanField(blank=True, null=True)),
                ('min_duration_in_group', models.PositiveIntegerField(default=0)),
                ('savings_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_rule', to='savings_group.savingsgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
