# Generated by Django 5.1.7 on 2025-04-05 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings_group', '0003_savingsgroupmember'),
        ('wallet', '0002_alter_wallet_owner_type_transaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='type',
            new_name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='withdrawalrule',
            name='exact_contribution_required',
        ),
        migrations.RemoveField(
            model_name='withdrawalrule',
            name='min_balance_required',
        ),
        migrations.RemoveField(
            model_name='withdrawalrule',
            name='min_duration_in_group',
        ),
        migrations.AddField(
            model_name='withdrawalrule',
            name='custom_rule_data',
            field=models.JSONField(blank=True, help_text='Optional field for storing custom logic or conditions', null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrule',
            name='min_group_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Group wallet must retain at least this amount', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrule',
            name='min_membership_days',
            field=models.PositiveIntegerField(default=0, help_text='Minimum number of days a user must be a group member to withdraw'),
        ),
        migrations.AddField(
            model_name='withdrawalrule',
            name='restrict_to_contribution',
            field=models.BooleanField(default=False, help_text="If True, user can't withdraw more than they've contributed"),
        ),
        migrations.AddField(
            model_name='withdrawalrule',
            name='static_dividend_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Static percentage (e.g., 5.00 means 5%) for dividends', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='owner_type',
            field=models.CharField(choices=[('user', 'user'), ('savings_group', 'savings_group')], max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawalrule',
            name='max_withdrawal_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum percent of wallet balance a user can withdraw', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrule',
            name='rule_description',
            field=models.TextField(help_text='Human-readable description of the rule'),
        ),
        migrations.AlterField(
            model_name='withdrawalrule',
            name='rule_type',
            field=models.CharField(choices=[('exact', 'Exact Contribution'), ('time_based', 'Time-based Contribution'), ('flexible', 'Flexible Withdrawal'), ('min_balance', 'Minimum Balance Requirement'), ('dividend_static', 'Static Percentage Dividend'), ('dividend_ratio', 'Dividend by Contribution Ratio'), ('custom', 'Custom (JSON-defined)')], help_text='Type of withdrawal rule logic to apply', max_length=30),
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('savings_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings_group.savingsgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
