# Generated by Django 5.1.7 on 2025-04-05 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings_group', '0003_savingsgroupmember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingsgroupmember',
            old_name='User',
            new_name='user',
        ),
    ]
