# Generated by Django 5.1.7 on 2025-04-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings_group', '0005_rename_savingsgroup_savingsgroupmember_savings_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingsgroupmember',
            old_name='savings_group',
            new_name='SavingsGroup',
        ),
        migrations.DeleteModel(
            name='Contribution',
        ),
    ]
