# Generated by Django 5.1.7 on 2025-04-13 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings_group', '0006_rename_savings_group_savingsgroupmember_savingsgroup_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingsgroupmember',
            old_name='SavingsGroup',
            new_name='savings_group',
        ),
    ]
